# Generated by Django 3.2.4 on 2021-11-07 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.centromedico'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.especialidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.perfil'),
        ),
    ]
